/**
 * PollPool Contract ABI
 * Inlined for deployment compatibility
 */

export const POLLPOOL_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_usdc", type: "address" },
      { internalType: "address", name: "_treasury", type: "address" },
      { internalType: "address", name: "_attestationSigner", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AlreadyParticipated", type: "error" },
  { inputs: [], name: "ECDSAInvalidSignature", type: "error" },
  { inputs: [{ internalType: "uint256", name: "length", type: "uint256" }], name: "ECDSAInvalidSignatureLength", type: "error" },
  { inputs: [{ internalType: "bytes32", name: "s", type: "bytes32" }], name: "ECDSAInvalidSignatureS", type: "error" },
  { inputs: [], name: "InvalidAddress", type: "error" },
  { inputs: [], name: "InvalidAmount", type: "error" },
  { inputs: [], name: "InvalidAttestation", type: "error" },
  { inputs: [], name: "InvalidDuration", type: "error" },
  { inputs: [], name: "InvalidParticipantCap", type: "error" },
  { inputs: [], name: "NotPollCreator", type: "error" },
  { inputs: [], name: "NothingToDistribute", type: "error" },
  { inputs: [{ internalType: "address", name: "owner", type: "address" }], name: "OwnableInvalidOwner", type: "error" },
  { inputs: [{ internalType: "address", name: "account", type: "address" }], name: "OwnableUnauthorizedAccount", type: "error" },
  { inputs: [], name: "ParticipantCapReached", type: "error" },
  { inputs: [], name: "PollAlreadyDistributed", type: "error" },
  { inputs: [], name: "PollNotActive", type: "error" },
  { inputs: [], name: "PollNotClosed", type: "error" },
  { inputs: [], name: "PollNotExpired", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [{ internalType: "address", name: "token", type: "address" }], name: "SafeERC20FailedOperation", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "oldSigner", type: "address" },
      { indexed: true, internalType: "address", name: "newSigner", type: "address" },
    ],
    name: "AttestationSignerUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "pollId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "participantCount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "payoutPerPerson", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "returnedToCreator", type: "uint256" },
    ],
    name: "FundsDistributed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
      { indexed: true, internalType: "address", name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "pollId", type: "uint256" },
      { indexed: true, internalType: "address", name: "creator", type: "address" },
      { indexed: false, internalType: "uint256", name: "refundedAmount", type: "uint256" },
    ],
    name: "PollCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "pollId", type: "uint256" },
      { indexed: true, internalType: "address", name: "closedBy", type: "address" },
      { indexed: false, internalType: "uint256", name: "finalParticipantCount", type: "uint256" },
    ],
    name: "PollClosed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "pollId", type: "uint256" },
      { indexed: true, internalType: "address", name: "creator", type: "address" },
      { indexed: false, internalType: "string", name: "title", type: "string" },
      { indexed: false, internalType: "bytes32", name: "criteriaHash", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "totalFunded", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "distributablePool", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "participantCap", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "expiresAt", type: "uint256" },
    ],
    name: "PollCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "pollId", type: "uint256" },
      { indexed: true, internalType: "address", name: "participant", type: "address" },
      { indexed: false, internalType: "uint256", name: "participantNumber", type: "uint256" },
    ],
    name: "ResponseSubmitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "oldTreasury", type: "address" },
      { indexed: true, internalType: "address", name: "newTreasury", type: "address" },
    ],
    name: "TreasuryUpdated",
    type: "event",
  },
  { inputs: [], name: "BPS_DENOMINATOR", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "PLATFORM_FEE_BPS", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "attestationSigner", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_pollId", type: "uint256" }], name: "calculatePayout", outputs: [{ internalType: "uint256", name: "payoutPerPerson", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_pollId", type: "uint256" }], name: "closePoll", outputs: [], stateMutability: "nonpayable", type: "function" },
  {
    inputs: [
      { internalType: "string", name: "_title", type: "string" },
      { internalType: "bytes32", name: "_criteriaHash", type: "bytes32" },
      { internalType: "uint256", name: "_participantCap", type: "uint256" },
      { internalType: "uint256", name: "_duration", type: "uint256" },
      { internalType: "uint256", name: "_fundAmount", type: "uint256" },
    ],
    name: "createPoll",
    outputs: [{ internalType: "uint256", name: "pollId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  { inputs: [{ internalType: "uint256", name: "_pollId", type: "uint256" }], name: "distribute", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_pollId", type: "uint256" }], name: "getParticipants", outputs: [{ internalType: "address[]", name: "", type: "address[]" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ internalType: "uint256", name: "_pollId", type: "uint256" }],
    name: "getPoll",
    outputs: [
      {
        components: [
          { internalType: "address", name: "creator", type: "address" },
          { internalType: "string", name: "title", type: "string" },
          { internalType: "bytes32", name: "criteriaHash", type: "bytes32" },
          { internalType: "uint256", name: "totalFunded", type: "uint256" },
          { internalType: "uint256", name: "distributablePool", type: "uint256" },
          { internalType: "uint256", name: "participantCap", type: "uint256" },
          { internalType: "uint256", name: "participantCount", type: "uint256" },
          { internalType: "uint256", name: "expiresAt", type: "uint256" },
          { internalType: "enum PollPool.PollStatus", name: "status", type: "uint8" },
        ],
        internalType: "struct PollPool.Poll",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [{ internalType: "uint256", name: "", type: "uint256" }, { internalType: "address", name: "", type: "address" }], name: "hasParticipated", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_pollId", type: "uint256" }], name: "isPollExpired", outputs: [{ internalType: "bool", name: "", type: "bool" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "nextPollId", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "owner", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "", type: "uint256" }, { internalType: "uint256", name: "", type: "uint256" }], name: "participants", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "polls",
    outputs: [
      { internalType: "address", name: "creator", type: "address" },
      { internalType: "string", name: "title", type: "string" },
      { internalType: "bytes32", name: "criteriaHash", type: "bytes32" },
      { internalType: "uint256", name: "totalFunded", type: "uint256" },
      { internalType: "uint256", name: "distributablePool", type: "uint256" },
      { internalType: "uint256", name: "participantCap", type: "uint256" },
      { internalType: "uint256", name: "participantCount", type: "uint256" },
      { internalType: "uint256", name: "expiresAt", type: "uint256" },
      { internalType: "enum PollPool.PollStatus", name: "status", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { inputs: [{ internalType: "uint256", name: "_pollId", type: "uint256" }], name: "refund", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "renounceOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "_newSigner", type: "address" }], name: "setAttestationSigner", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "_newTreasury", type: "address" }], name: "setTreasury", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_pollId", type: "uint256" }, { internalType: "bytes", name: "_attestationSignature", type: "bytes" }], name: "submitResponse", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "newOwner", type: "address" }], name: "transferOwnership", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "treasury", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "usdc", outputs: [{ internalType: "contract IERC20", name: "", type: "address" }], stateMutability: "view", type: "function" },
];
